version: "3"
services:
  webserver:
    build:
      context: ./http-server
    volumes:
    - ./http-server/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - ./http-server/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
    ports:
    - 80:80
    - 443:443
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    # you can use image or custom build below
    image: nabo.codimd.dev/hackmdio/hackmd:2.0.0
    environment:
      - CMD_DB_URL=postgres://codimd:change_password@database/codimd
      - CMD_USECDN=false
      - CMD_DOMAIN=md.example.com
      - CMD_URL_PATH=internal-codimd
      - CMD_PROTOCOL_USESSL=true
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
